//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSgrupp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourceModels
    {
        public CourceModels()
        {
            this.StudentModels = new HashSet<StudentModels>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string TeacherId { get; set; }
        public string StudentNumber { get; set; }
        public Nullable<int> FileModel_Id { get; set; }
        public string Teacher_EmplymentNumber { get; set; }
        public Nullable<int> SchemaModel_Id { get; set; }
    
        public virtual FileModels FileModels { get; set; }
        public virtual SchemaModels SchemaModels { get; set; }
        public virtual TeacherModels TeacherModels { get; set; }
        public virtual ICollection<StudentModels> StudentModels { get; set; }
    }
}
