//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSgrupp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileModels
    {
        public FileModels()
        {
            this.CourceModels = new HashSet<CourceModels>();
            this.StudentModels = new HashSet<StudentModels>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public System.DateTime Date { get; set; }
        public bool Shared { get; set; }
        public int CourceId { get; set; }
        public string StudentNumber { get; set; }
    
        public virtual ICollection<CourceModels> CourceModels { get; set; }
        public virtual ICollection<StudentModels> StudentModels { get; set; }
    }
}
