//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSgrupp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemaModels
    {
        public SchemaModels()
        {
            this.CourceModels = new HashSet<CourceModels>();
        }
    
        public int Id { get; set; }
        public string TeacherId { get; set; }
        public int CourceId { get; set; }
        public string Location { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ICollection<CourceModels> CourceModels { get; set; }
        public virtual TeacherModels TeacherModels { get; set; }
    }
}
