//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSgrupp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherModels
    {
        public TeacherModels()
        {
            this.CourceModels = new HashSet<CourceModels>();
            this.SchemaModels = new HashSet<SchemaModels>();
        }
    
        public string EmplymentNumber { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Town { get; set; }
        public string ZipCode { get; set; }
        public string Email { get; set; }
        public int CourceId { get; set; }
    
        public virtual ICollection<CourceModels> CourceModels { get; set; }
        public virtual ICollection<SchemaModels> SchemaModels { get; set; }
    }
}
