// <auto-generated />
namespace LMSgrupp3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Initiaial777 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initiaial777));
        
        string IMigrationMetadata.Id
        {
            get { return "201602041223502_Initiaial777"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
